# Generated by Django 5.1.7 on 2025-03-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
    ]
