# Generated by Django 5.1.7 on 2025-03-27 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_subscription_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
    ]
