# Generated by Django 5.1.7 on 2025-03-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='sub_discount',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='types',
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default=20, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.PositiveIntegerField(choices=[(500, '500'), (1000, '1000')], editable=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
