# Generated by Django 5.1.7 on 2025-03-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_subscription_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.PositiveIntegerField(choices=[(1000, '1000'), (2000, '2000')], editable=False),
        ),
    ]
