# Generated by Django 5.1.7 on 2025-04-17 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_subscription_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='user',
            new_name='buyer',
        ),
    ]
