# Generated by Django 5.1.7 on 2025-03-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_addresses_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
