# Generated by Django 5.1.7 on 2025-03-27 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_addresses_options_alter_vendorprofile_options_and_more'),
        ('orders', '0004_remove_subscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.subscription'),
        ),
    ]
