# Generated by Django 5.1.7 on 2025-04-09 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_shopuser_subscription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='addresses',
            unique_together=set(),
        ),
    ]
