services:
  web:
    container_name: django_project
    build:
      context: ./
      dockerfile: DockerFile
    command: sh -c "python manage.py migrate && gunicorn arzanshop.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - ./media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${DATABASE_URL}
    networks:
      - mynetwork
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
  redis:
    image: redis:latest
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data: