FROM python:3.12-alpine

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt
COPY . /app/

RUN pip install --upgrade pip
RUN pip install -r req.txt

EXPOSE 8000

CMD ["gunicorn", "arzanshop.wsgi:application", "--bind", "0.0.0.0:8000"]
