FROM python:3.12-alpine

WORKDIR /app

COPY ./req.txt /app/req.txt
COPY . /app/

RUN pip install --upgrade pip
RUN pip install -r req.txt

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]