# Generated by Django 5.1.7 on 2025-03-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
    ]
