# Generated by Django 5.1.5 on 2025-02-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_created_at_product_created_product_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='nothing'),
            preserve_default=False,
        ),
    ]
