# Generated by Django 5.1.5 on 2025-02-08 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_discounted_price_discount_usage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='usage',
        ),
    ]
