# Generated by Django 5.1.7 on 2025-03-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='product',
            new_name='products',
        ),
    ]
