# Generated by Django 5.1.5 on 2025-02-10 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
